### ISSUE TITLE
can't load library

### ISSUE THREAD

**Issue by bazworkshops** [wbrent/timbreID#1]
Hi, I've been dealing with this for some hours. The earlier version of TimbreID works fine on my old Mac, but I'm unable to load the timbreIDLib.dll in Windows. The complaints haven't changed with the version you uploaded two hours ago. I have the dll in the startup of Pure Data, and know it's trying to load because of the error message in the console on startup. This Windows machine is sooo much faster than my old Mac and I'd love to bring it to ICMC tonight instead. Here are some details: Pd 0.48.1 (32-bit), Windows 10 1803.
Cheers,
Barry Moon

**Comment by wbrent** [comment]
Hi Barry, thanks for writing.When you say that the previous version worked fine, which version do you mean? Was the previous version 0.7 or higher (with a single timbreIDLib.pd_darwin binary)?Pulling version 0.7.6 via deken is working fine on my similar Windows setup. Are you getting the deken package, or cloning the GitHub repo? I'm not on that machine right now and can't check the exact path I gave in the Startup dialog, but I believe it is:C:/Users/w/Documents/Pd/externals/timbreID/timbreIDLibI do know that you shouldn't append the .dll extension when listing the path and file, so perhaps that's it? The other issue I remember dealing with is that Pd expects paths to be given with forward slash separators, while in the rest of Windows, backslashes are the convention. Maybe you already know all this...no idea. But that's at least a start. Let me know if it works out or if you have some other questions. I have Windows 10 and am also running Pd 0.48-1 32bit...no problems.--------------------------------William BrentAssociate Professor of Audio TechnologyAmerican University, Washington DCwww.williambrent.comOn August 3, 2018 at 11:32 AM bazworkshops <notifications@github.com> wrote:  Hi, I've been dealing with this for some hours. The earlier version of TimbreID works fine on my old Mac, but I'm unable to load the timbreIDLib.dll in Windows. The complaints haven't changed with the version you uploaded two hours ago. I have the dll in the startup of Pure Data, and know it's trying to load because of the error message in the console on startup. This Windows machine is sooo much faster than my old Mac and I'd love to bring it to ICMC tonight instead. Here are some details: Pd 0.48.1 (32-bit), Windows 10 1803. Cheers, Barry Moon—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bazworkshops** [comment]
Hi William,
No, I didn't know about ommitting the .dll from the path in startup. That was it! Fixed! If you're at ICMC, or whenever our paths cross, I owe you a beer or three.
Cheers,
Barry

**Comment by wbrent** [comment]
Excellent! Glad it worked out. Not there for this ICMC, but likely next year. Two beers will suffice ;)


-------- Original message --------From: bazworkshops <notifications@github.com> Date: 8/3/18  1:03 PM  (GMT-05:00) To: wbrent/timbreID <timbreID@noreply.github.com> Cc: wbrent <w@williambrent.com>, Comment <comment@noreply.github.com> Subject: Re: [wbrent/timbreID] can't load library (#1) 
Hi William,

No, I didn't know about ommitting the .dll from the path in startup. That was it! Fixed! If you're at ICMC, or whenever our paths cross, I owe you a beer or three.

Cheers,

Barry

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wbrent/timbreID","title":"wbrent/timbreID","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/wbrent/timbreID"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bazworkshops in #1: Hi William,\r\nNo, I didn't know about ommitting the .dll from the path in startup. That was it! Fixed! If you're at ICMC, or whenever our paths cross, I owe you a beer or three.\r\nCheers,\r\nBarry"}],"action":{"name":"View Issue","url":"https://github.com/wbrent/timbreID/issues/1#issuecomment-410315967"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wbrent/timbreID/issues/1#issuecomment-410315967",
"url": "https://github.com/wbrent/timbreID/issues/1#issuecomment-410315967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [wbrent/timbreID] can't load library (#1)",
"sections": [
{
"text": "",
"activityTitle": "**bazworkshops**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@bazworkshops",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"wbrent/timbreID\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"wbrent/timbreID\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/wbrent/timbreID/issues/1#issuecomment-410315967"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364432365\n}"
}
],
"themeColor": "26292E"
}
]
